### ISSUE TITLE
Reduce instance variables in TmdbHandler and tmdb_controller

### ISSUE THREAD

**Issue by lortza** [mikevallano/tmdb-moviequeue#270]
While implementing some new features recently that we have a lot of instance variables being generated by the `lib/tmdb_handler.rb` file. This is problematic because they end up way down stream in places we do not expect. This is a big job and we're chipping away at it a few methods at a time.

### `TmdbHandler` Methods to refactor 
- [x] `tmdb_handler_search` PR #267
- [x] `tmdb_handler_movie_autocomplete` PR #269
- [x] `tmdb_handler_person_autocomplete` PR #269
- [x] [`tmdb_handler_movie_more`](https://github.com/mikevallano/tmdb-moviequeue/issues/268) PR #277
- [x] [`tmdb_handler_full_cast`](https://github.com/mikevallano/tmdb-moviequeue/issues/271) PR #272
- [x] [`tmdb_handler_add_movie`](https://github.com/mikevallano/tmdb-moviequeue/issues/273) PR #276
- [x] `self.tmdb_handler_update_movie`
- [x] `tmdb_handler_person_detail_search`
- [x] `tmdb_handler_actor_credit` PR #252
- [x] `tmdb_handler_tv_series_search`
- [x] `tmdb_handler_tv_series_autocomplete`
- [x] `tmdb_handler_tv_series` PR #251
- [x] `tmdb_handler_tv_season` PR #251
- [x] `tmdb_handler_tv_episode` PR #254
- [x] `tmdb_handler_two_movie_search` PR #267
- [x] [`tmdb_handler_discover_search`](https://github.com/mikevallano/tmdb-moviequeue/issues/274)
  - PR #279
  - PR #298
  - PR #291
  - PR #296
